stages:
  - test

testJava7:
  tags:
    - docker
  image: gradle:4.10-jdk7
  stage: test
  script: gradle --no-daemon -b build.java7.gradle check

testJava8:
  tags:
    - docker
  image: gradle:4.10-jdk8
  stage: test
  script: gradle --no-daemon check

testJava10:
  tags:
    - docker
  image: gradle:4.10-jdk10
  stage: test
  script: gradle --no-daemon check

testJava11:
  tags:
    - docker
  image: gradle:4.10-jdk11
  stage: test
  script: gradle --no-daemon check
  when: manual

verifyJSONTestSuite:
  tags:
    - docker
  image: gradle:4.10-jdk10
  stage: test
  script: gradle verifyJSONTestSuite
